name: battery_plus pages

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        run: |
          melos bootstrap --scope="battery_plus"
          melos exec -c 1 --scope="battery_plus_example" -- flutter build web --base-href "/plus_plugins/"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/battery_plus/battery_plus/example/build/web
